version: '3'
services:
  shopper-mariaDB:
    image: mariadb:latest
    container_name: mamad-mariaDB
    volumes:
      - mamad-mariaDB:/var/lib/mysql/
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - mamad_network

volumes:
  mamad-mariaDB:
    external: true

networks:
  mamad_network:
    external: true
