# Generated by Django 3.1.4 on 2020-12-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_main.product'),
        ),
    ]
